version: '3'

services:
  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "
        mkdir -p public static &&
        [ ! -f public/index.html ] && echo '<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>CV Website</title></head><body><div id=\"root\"></div></body></html>' > public/index.html || true &&
        npm install &&
        npm run build || echo 'Build failed!' && 
        if [ -d 'build' ]; then echo 'Build directory contents:' && ls -la build/ && cp -r build/* /app/build/; else echo 'Build directory not found!'; fi
      "
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
    volumes:
      - ./static:/app/static:ro
      - ./build:/app/build
      - ./content.yaml:/app/content.yaml
    command: >
      sh -c "
        echo 'Waiting for frontend build to complete...' &&
        until [ -f /app/build/index.html ] || [ -f /app/build/static/js/main.*.js ]; do
          echo 'Waiting for build files...' &&
          ls -la /app/build || echo 'Build directory empty or not found' &&
          sleep 5;
        done &&
        echo 'Frontend build detected, starting server...' &&
        ls -la /app/build &&
        gunicorn --bind 0.0.0.0:5000 app:app
      "
    depends_on:
      - frontend

# # Email test service
#   email-test:
#     build:
#       context: .
#       dockerfile: Dockerfile.backend
#     volumes:
#       - .:/app
#     environment:
#       - EMAIL_USER=${EMAIL_USER}
#       - EMAIL_PASS=${EMAIL_PASS}
#       - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
#     command: python /app/test_email.py 